apiVersion: v1
kind: ConfigMap
metadata:
  name: bodygpt-config
  namespace: default
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  AUTH_SERVICE_PORT: "5001"
  USER_SERVICE_PORT: "5002"
  DIET_SERVICE_PORT: "5003"
  WORKOUT_SERVICE_PORT: "5004"
  CHATBOT_SERVICE_PORT: "5005"
  PROGRESS_SERVICE_PORT: "5006"
  YOLO_EXERCISE_PORT: "8001"
  FOOD_RECOGNITION_PORT: "8002"
