apiVersion: v1
kind: Secret
metadata:
  name: bodygpt-secrets
  namespace: default
type: Opaque
stringData:
  MONGO_URI: "mongodb://fitcosmos:ZV6VcQOxLwbiI2y5CM5i7k2g3tqwz4ZZmnCerTyLR1R8FD9GaEWdN9PJRdpZzF6WQr1Ucpg8e4CrACDbvWOzoQ==@fitcosmos.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@fitcosmos@"
  JWT_ACCESS_SECRET: "bodygpt_access_secret_12345!"
  JWT_REFRESH_SECRET: "bodygpt_refresh_secret_12345!"
  AZURE_OPENAI_API_KEY: "371mSSorSVYx4P9qNMT1oHmTnyJjZLKWurXkBXG61HGV0hV42JTWJQQJ99CFACHYHv6XJ3w3AAAAACOGvsQD"
  AZURE_AI_FOUNDRY_ENDPOINT: "https://cloud-ai-resource.services.ai.azure.com/"
  AZURE_SERVICEBUS_CONNECTION_STRING: "Endpoint=sb://servicebus1243.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=aNIMEeVANkGgoDg7uZywkEUNDugfWc/3v+ASbJ6eiTM="
  AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=storebodygptprod;AccountKey=MN+6a/7j+s12Oww3rAARuRF1DUh6ch1M/MF5r/yA3wpiDcvbmTmtfFaVbZ4yl9FZGcBhsnB0yzJU+AStDF28zQ==;EndpointSuffix=core.windows.net"
  SMTP_USER: "aravindroyal2002@gmail.com"
  SMTP_PASS: "hgtsakpxwafgjenl"
  AZURE_AI_SEARCH_ENDPOINT: "https://fitbuddy-search-xyz.search.windows.net"
  AZURE_AI_SEARCH_KEY: "w4rfiIOEtekOF3Bx8iu4rMYESAE1UOJfoqBcRJjL79AzSeCmDv9d"
