apiVersion: v1
kind: Secret
metadata:
  name: bodygpt-secrets
  namespace: default
type: Opaque
stringData:
  MONGO_URI: "YOUR_COSMOS_CONNECTION_STRING"
  JWT_ACCESS_SECRET: "bodygpt_access_secret_12345!"
  JWT_REFRESH_SECRET: "bodygpt_refresh_secret_12345!"
  AZURE_OPENAI_API_KEY: "YOUR_AZURE_OPENAI_KEY"
  AZURE_AI_FOUNDRY_ENDPOINT: "YOUR_AZURE_OPENAI_ENDPOINT"
  AZURE_SERVICEBUS_CONNECTION_STRING: "YOUR_SERVICE_BUS_CONNECTION_STRING"
  AZURE_STORAGE_CONNECTION_STRING: "YOUR_STORAGE_CONNECTION_STRING"
  SMTP_USER: "YOUR_EMAIL"
  SMTP_PASS: "YOUR_EMAIL_PASSWORD"
  AZURE_AI_SEARCH_ENDPOINT: "YOUR_AI_SEARCH_ENDPOINT"
  AZURE_AI_SEARCH_KEY: "YOUR_AI_SEARCH_KEY"
